USE biggym;

INSERT INTO products (
  name, slug, category_name, category_slug, price, sale_price, stock_quantity,
  image_url, badge_label, short_description, is_featured, is_active, sort_order
) VALUES
  (
    'Elite Gold Protein',
    'elite-gold-protein',
    'Whey Isolate',
    'whey',
    2450000,
    2190000,
    18,
    '../assets/images/products/elite-gold-protein/butterscotch.jpg',
    'Bán chạy',
    'Whey isolate tinh sạch cho giai đoạn tăng cơ nạc và phục hồi nhanh.',
    1,
    1,
    10
  ),
  (
    'OstroVit 100% Whey Protein Isolate',
    'ostrovit-100-whey-protein-isolate',
    'Hydrolyzed Whey',
    'whey',
    1390000,
    1290000,
    12,
    '../assets/images/products/ostrovit-100-whey-protein-isolate/chocolate.png',
    'Premium',
    'Dòng whey hấp thu nhanh dành cho giai đoạn siết cơ và hồi phục sau buổi tập.',
    1,
    1,
    20
  ),
  (
    'OstroVit Creatine Monohydrate',
    'ostrovit-creatine-monohydrate',
    'Creatine',
    'creatine',
    850000,
    NULL,
    24,
    '../assets/images/products/ostrovit-creatine-monohydrate/green-apple.png',
    'Hiệu suất',
    'Creatine monohydrate dạng bột hỗ trợ sức mạnh, công suất và hiệu suất tập luyện cường độ cao.',
    1,
    1,
    30
  ),
  (
    'OstroVit PUMP Pre-Workout Formula',
    'ostrovit-pump-pre-workout-formula',
    'Pre-Workout',
    'preworkout',
    1150000,
    990000,
    16,
    '../assets/images/products/ostrovit-pump-pre-workout-formula/watermelon.png',
    'Năng lượng',
    'Pre-workout công thức 8 thành phần hỗ trợ tập trung, pump cơ và hiệu suất trước buổi tập.',
    1,
    1,
    40
  ),
  (
    'OstroVit 100% VIT&MIN',
    'ostrovit-100-vit-min',
    'Vitamin',
    'vitamin',
    1200000,
    NULL,
    20,
    '../assets/images/products/ostrovit-100-vit-min/tablets.png',
    'Hồi phục',
    'Multivitamin và khoáng chất tổng hợp giúp bổ sung vi chất thiết yếu cho sinh hoạt và tập luyện hằng ngày.',
    0,
    1,
    50
  ),
  (
    'OstroVit Omega 3 Extreme',
    'ostrovit-omega-3-extreme',
    'Omega 3',
    'vitamin',
    980000,
    NULL,
    14,
    '../assets/images/products/ostrovit-omega-3-extreme/softgel.png',
    'Hàng mới',
    'Omega 3 Extreme dạng softgel cung cấp EPA và DHA hỗ trợ tim mạch, não bộ và nền phục hồi tổng thể.',
    0,
    1,
    60
  ) AS new
ON DUPLICATE KEY UPDATE
  name = new.name,
  category_name = new.category_name,
  category_slug = new.category_slug,
  price = new.price,
  sale_price = new.sale_price,
  stock_quantity = new.stock_quantity,
  image_url = new.image_url,
  badge_label = new.badge_label,
  short_description = new.short_description,
  is_featured = new.is_featured,
  is_active = new.is_active,
  sort_order = new.sort_order;
